### PR TITLE
Header

### PR DESCRIPTION
**Pull request by cassiemak**

### CODE REVIEW

**Comment by cassiemak** [comment]
Please approve now that all the layout is set. Thanks!

**Comment by h8rry** [comment]
@cassiemak Looks good. Please rebase and merge yourself.

**Comment by cassiemak** [comment]
Can't we just merge both #17 and #18 and then pull request from master locally all together? 
Or we have to do it one by one?

**Comment by h8rry** [comment]
Better to do it one by one

**Comment by cassiemak** [comment]
OK... 
locally, i have pull request #17 to my master
so i should go to my header branch and then rebase? then commit and push again to git hub?
and then merge on git hub?
and then go to master locally to pull request? 

is that right?

**Comment by h8rry** [comment]
1. git checkout master
2. git pull origin master
3. git checkout header
4. git rebase header
5. git push origin header
6. merge on github

**Pull request merged**
